name: Build

on:
  workflow_call:
    inputs:
      aws-region:
        description: 'AWS Region'
        default: 'eu-west-2'
        required: true
        type: string

      aws-iam-role:
        description: 'AWS IAM Role To Assume'
        required: true
        type: string

      dockerfile:
        description: 'Dockerfile'
        default: './Dockerfile'
        required: false
        type: string

      docker-image:
        description: 'Docker Image Name'
        required: true
        type: string

      platforms:
        description: 'Docker Platforms'
        default: 'linux/arm64'
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-iam-role }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate tags
        id: tag
        uses: paulhatch/semantic-version@v5.0.2

      - name: Set Tag Versions
        run: |
          echo "GIT_CURRENT_TAG=v${{ steps.tag.outputs.previous_version }}-${{ github.run_id }}" >> $GITHUB_ENV
          if [[ -f package.json ]]
          then
            if [[ $(jq keys package.json | grep -c 'version') -eq 1 ]]
            then
              echo "PACKAGE_VERSION=$(jq -r .version package.json)-${{ github.run_id }}" >> $GITHUB_ENV
            fi
          fi

      - name: Choose Tag
        run: |
          if [[ -z ${PACKAGE_VERSION} ]]
          then
            echo "DOCKER_TAG=${GIT_CURRENT_TAG}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${PACKAGE_VERSION}" >> $GITHUB_ENV
          fi

      - name: Environment Checks
        run: |
          echo GIT_CURRENT_TAG=${GIT_CURRENT_TAG}
          echo PACKAGE_VERSION=${PACKAGE_VERSION}
          echo DOCKER_TAG=${DOCKER_TAG}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          platforms: ${{ inputs.platforms }}
          provenance: false
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.docker-image }}:${{ env.DOCKER_TAG }}
